### ISSUE TITLE
Dropping binaries to disk and not cleaning up

### ISSUE THREAD

**Issue by SecurityJon** [Fadi002/unshackle#10]
The tool searches for the sethc.exe binary on the mounted Windows drive, then renames it and drops it's own binary in place before rebooting. 

This leaves the user with a backdoor on the system as I don't see any clean up occurring, which could later be picked up by AV and removed - which removes Windows functionality.

A post-run script should fix this before permitting Windows to boot again.

**Comment by Fadi002** [comment]
> The tool searches for the sethc.exe binary on the mounted Windows drive, then renames it and drops it's own binary in place before rebooting. 
> 
> This leaves the user with a backdoor on the system as I don't see any clean up occurring, which could later be picked up by AV and removed - which removes Windows functionality.
> 
> A post-run script should fix this before permitting Windows to boot again.

Cool feature i will add it in the next update

**Comment by Fadi002** [comment]
> Looking forward to the Linux version
done
