### ISSUE TITLE
How is the unshackle bin compiled? I would like to make changes

### ISSUE THREAD

**Issue by dotaxis** [Fadi002/unshackle#11]

**Comment by Fadi002** [comment]
To compile the Unshackle Bin and make changes, you'll need to follow these steps on Alpine Linux:
Download the standard Alpine Linux
Here's the link to download Alpine Linux: https://www.alpinelinux.org/downloads/ 
After setting it up on VM or your PC Do the following steps :
1. Install python, psutil and pyinstaller:
```bash
apk add linux-headers
apk add python3-full
pip install pyinstaller psutil
```
2. Download Unshackle Bin source code or repository
3. Make your desired changes to the source code.
4. Compile the Unshackle Bin using pyinstaller:
```bash
pyinstaller --onefile unshackle.py
```
Now you have a compiled version of Unshackle Bin with your modifications. Remember to test it thoroughly before distributing or using it
