### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Kevin3-00** [Fadi002/unshackle#2]
After it finished,it showed now window booting medium found and I followed all the instructions.

**Comment by Fadi002** [comment]
> After it finished,it showed now window booting medium found and I followed all the instructions.

I didn't understand what you meant can you send a picture of the error or something?

**Comment by Zugidor** [comment]
Just to add on to the issue that v1 doesn't seem to be working. In my case, I can't boot from the USB after writing the ISO to it with Rufus because no drive letter is assigned. It doesn't show up in the UEFI/BIOS for boot order, nor in file explorer. I can't assign a drive letter in disk management either. Additionally, Rufus displays a warning when selecting the ISO. See below images. 

![Screenshot 2023-07-22 143134](https://github.com/Fadi002/unshackle/assets/72618685/31d75465-aa7d-47a4-9761-7c0e4eb117b2)
![Screenshot 2023-07-22 142721](https://github.com/Fadi002/unshackle/assets/72618685/f6212ecf-8df8-4556-a0b7-feb70ff3c472)
![Screenshot 2023-07-22 142643](https://github.com/Fadi002/unshackle/assets/72618685/5626c7a8-89fb-48dc-b365-f2eac2cd7420)
![Screenshot 2023-07-22 142505](https://github.com/Fadi002/unshackle/assets/72618685/9c89809e-0f5f-4618-93db-81d182a83bd5)

It seems that after burning the ISO, there is some issue that renders the USB unbootable because no drive letter can be assigned.
Below is a log from Rufus, in case it's useful:
```
Found USB 3.0 device 'SanDisk Ultra USB Device' (0781:5581)
1 device found
No volume information for drive 0x81
Disk type: Removable, Disk size: 64 GB, Sector size: 512 bytes
Cylinders: 7477, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000000
Drive has an unknown Master Boot Record
Partition 1:
  Type: ISOHybrid (0xcd)
  Detected File System: (Unrecognized)
  Size: 57.3 MB (60093952 bytes)
  Start Sector: 1, Boot: Yes
Scanning image...
ISO analysis:
  Image is an ISO9660 image
  Reported Grub version:
  Could not detect Grub version
Disk image analysis:
  Image has an unknown Master Boot Record
  Image is a bootable disk image
ISO label: 'ISOIMAGE'
  Size: 56.9 MB (Projected)
Note: DD image mode enforced since this ISOHybrid is not ISO mode compatible.
Using image: unshackle-v1.0.iso (57.3 MB)
```

**Comment by Kevin3-00** [comment]
> > After it finished,it showed now window booting medium found and I followed all the instructions.
> 
> I didn't understand what you meant can you send a picture of the error or something?

![PHOTO1](https://github.com/Fadi002/unshackle/assets/55138595/c06b007c-2163-4c05-8a4d-3a64c3ba06e1)
![photo_2023-07-22_07-01-53](https://github.com/Fadi002/unshackle/assets/55138595/578d7141-3413-48a4-b1fe-5009d90bc3f4)

**Comment by Kevin3-00** [comment]
This happened after I had booted in to unshakle.My window is clean and licenced.

**Comment by Fadi002** [comment]
> This happened after I had booted in to unshakle.My window is clean and licenced.

sorry, but unfortunately we don't support drives that have encryption enabled, so maybe you have BitLocker or similar drive encryption software on your machine?

**Comment by Fadi002** [comment]
> Just to add on to the issue that v1 doesn't seem to be working. In my case, I can't boot from the USB after writing the ISO to it with Rufus because no drive letter is assigned. It doesn't show up in the UEFI/BIOS for boot order, nor in file explorer. I can't assign a drive letter in disk management either. Additionally, Rufus displays a warning when selecting the ISO. See below images. 
> 
> ![Screenshot 2023-07-22 143134](https://github.com/Fadi002/unshackle/assets/72618685/31d75465-aa7d-47a4-9761-7c0e4eb117b2)
> ![Screenshot 2023-07-22 142721](https://github.com/Fadi002/unshackle/assets/72618685/f6212ecf-8df8-4556-a0b7-feb70ff3c472)
> ![Screenshot 2023-07-22 142643](https://github.com/Fadi002/unshackle/assets/72618685/5626c7a8-89fb-48dc-b365-f2eac2cd7420)
> ![Screenshot 2023-07-22 142505](https://github.com/Fadi002/unshackle/assets/72618685/9c89809e-0f5f-4618-93db-81d182a83bd5)
> 
> It seems that after burning the ISO, there is some issue that renders the USB unbootable because no drive letter can be assigned.
> Below is a log from Rufus, in case it's useful:
> ```
> Found USB 3.0 device 'SanDisk Ultra USB Device' (0781:5581)
> 1 device found
> No volume information for drive 0x81
> Disk type: Removable, Disk size: 64 GB, Sector size: 512 bytes
> Cylinders: 7477, Tracks per cylinder: 255, Sectors per track: 63
> Partition type: MBR, NB Partitions: 1
> Disk ID: 0x00000000
> Drive has an unknown Master Boot Record
> Partition 1:
>   Type: ISOHybrid (0xcd)
>   Detected File System: (Unrecognized)
>   Size: 57.3 MB (60093952 bytes)
>   Start Sector: 1, Boot: Yes
> Scanning image...
> ISO analysis:
>   Image is an ISO9660 image
>   Reported Grub version:
>   Could not detect Grub version
> Disk image analysis:
>   Image has an unknown Master Boot Record
>   Image is a bootable disk image
> ISO label: 'ISOIMAGE'
>   Size: 56.9 MB (Projected)
> Note: DD image mode enforced since this ISOHybrid is not ISO mode compatible.
> Using image: unshackle-v1.0.iso (57.3 MB)
> ```

so you can't boot from your USB Drive and there's no errors showing? for the rendering problem then it's rufus problem, just delete the partitions then repartition it again. also what is your CPU Type (Arm, etc)?

**Comment by Zugidor** [comment]
> so you can't boot from your USB Drive and there's no errors showing? for the rendering problem then it's rufus problem, just delete the partitions then repartition it again. also what is your CPU Type (e.g. ARM)?

Yeah, I can't boot from the USB drive, even after I managed to assign a drive letter to it (it's still left unlabelled). To access it in file explorer, windows asks to format the 57MB partition where the ISO is. There's no problem with the burning process or drive since Rufus didn't report any read or write errors. I cleared partitions and reformatted the drive and it works fine. Tried burning it again and it doesn't work as before. I have an Intel CPU, I'm on Windows 11 Pro 64-bit licensed. I don't know if this is a problem with this specific USB drive, I'll try with another one now.

**Comment by joe865** [comment]
I'm facing the-same issue too when i flash with rufus I can't boot the usb from bios 

so i tried using it on ventoy to run the iso directly it appears to load but I only see the program heading 

"unshackle 1.0"

its like that for hours and it doesn't progress 

that's all i observed

**Comment by Zugidor** [comment]
> > so you can't boot from your USB Drive and there's no errors showing? for the rendering problem then it's rufus problem, just delete the partitions then repartition it again. also what is your CPU Type (e.g. ARM)?
> 
> Yeah, I can't boot from the USB drive, even after I managed to assign a drive letter to it (it's still left unlabelled). To access it in file explorer, windows asks to format the 57MB partition where the ISO is. There's no problem with the burning process or drive since Rufus didn't report any read or write errors. I cleared partitions and reformatted the drive and it works fine. Tried burning it again and it doesn't work as before. I have an Intel CPU, I'm on Windows 11 Pro 64-bit licensed. I don't know if this is a problem with this specific USB drive, I'll try with another one now.
> 

Update: attempted with another USB drive, a 32GB one from a different brand, and exact same issue. Shows up as `NO_LABEL` on Rufus, inaccessible in file explorer, uneditable in Windows disk management, unbootable. Re-formatting the drive returns it to a normal usable storage drive without issues. I burned Windows 10 installation media to this drive previously without any problems. Using latest Rufus 4.1

**Comment by Fadi002** [comment]
@Zugidor  @joe865 
can you try to enable EFI + UEFI from the motherboard settings ?

**Comment by Zugidor** [comment]
> can you try to enable EFI + UEFI from the motherboard settings ?

My motherboard is already UEFI enabled. But I did find that apparently Secure Boot might prevent "untrusted operating systems from loading during system start-up". I'll try disabling Secure Boot and seeing if it helps.

**Comment by Fadi002** [comment]
> > can you try to enable EFI + UEFI from the motherboard settings ?
> 
> My motherboard is already UEFI enabled. But I did find that apparently Secure Boot might prevent "untrusted operating systems from loading during system start-up". I'll try disabling Secure Boot and seeing if it helps.

Enable both (UEFI+EFI) and try

**Comment by Zugidor** [comment]
Ok, so in my experience (trying on both my desktop PC and my laptop) the following steps helped to get unshackle to boot and run:

1. if drive is encrypted (bitlocker or veracrypt), then disable drive encryption 
2. disable secure boot in BIOS
3. disable fast boot in BIOS
4. switch from windows UEFI -> legacy OS/custom OS in BIOS

In some BIOSes, 3 and 4 disable secure boot. 4 is necessary to allow booting into the unshackle USB (otherwise it doesn't appear in boot options).

So unshackle ran successfully, I rebooted, but after pressing shift five times on the login screen, nothing seemed to happen. It just seemed to disable my PIN and fingerprint reader logins (fingerprint reader login asked to use PIN, PIN said something went wrong and it needed to be reset). I ended up needing to log in with my password. After restarting and not changing anything, and not pressing shift five times, fingerprint and PIN worked fine. I removed fingerprint and PIN, re-ran unshackle again, rebooted, pressed shift five times on the lock screen, and no effect. My password was still necessary to log in.

**Comment by Fadi002** [comment]
> Ok, so in my experience (trying on both my desktop PC and my laptop) the following steps helped to get unshackle to boot and run:
> 
> 1. if drive is encrypted (bitlocker or veracrypt), then disable drive encryption 
> 2. disable secure boot in BIOS
> 3. disable fast boot in BIOS
> 4. switch from windows UEFI -> legacy OS/custom OS in BIOS
> 
> In some BIOSes, 3 and 4 disable secure boot. 4 is necessary to allow booting into the unshackle USB (otherwise it doesn't appear in boot options).
> 
> So unshackle ran successfully, I rebooted, but after pressing shift five times on the login screen, nothing seemed to happen. It just seemed to disable my PIN and fingerprint reader logins (fingerprint reader login asked to use PIN, PIN said something went wrong and it needed to be reset). I ended up needing to log in with my password. After restarting and not changing anything, and not pressing shift five times, fingerprint and PIN worked fine. I removed fingerprint and PIN, re-ran unshackle again, rebooted, pressed shift five times on the lock screen, and no effect. My password was still necessary to log in.

If you have online account then its impossible to bypass the password so just create a new account with administrator permissions
Just type !shell it should open a cmd for you and type these commands


net user [username] [password] /add
net localgroup administrators [username] /add

**Comment by Zugidor** [comment]
> > Ok, so in my experience (trying on both my desktop PC and my laptop) the following steps helped to get unshackle to boot and run:
> > 
> > 1. if drive is encrypted (bitlocker or veracrypt), then disable drive encryption 
> > 2. disable secure boot in BIOS
> > 3. disable fast boot in BIOS
> > 4. switch from windows UEFI -> legacy OS/custom OS in BIOS
> > 
> > In some BIOSes, 3 and 4 disable secure boot. 4 is necessary to allow booting into the unshackle USB (otherwise it doesn't appear in boot options).
> > 
> > So unshackle ran successfully, I rebooted, but after pressing shift five times on the login screen, nothing seemed to happen. It just seemed to disable my PIN and fingerprint reader logins (fingerprint reader login asked to use PIN, PIN said something went wrong and it needed to be reset). I ended up needing to log in with my password. After restarting and not changing anything, and not pressing shift five times, fingerprint and PIN worked fine. I removed fingerprint and PIN, re-ran unshackle again, rebooted, pressed shift five times on the lock screen, and no effect. My password was still necessary to log in.
> 
> If you have online account then its impossible to bypass the password so just create a new account with administrator permissions
> Just type !shell it should open a cmd for you and type these commands
> 
> 
> net user [username] [password] /add
> net localgroup administrators [username] /add
> 

I don't use any online Microsoft account. I'm using a local administrator account on all my computers.

**Comment by Fadi002** [comment]
> > > Ok, so in my experience (trying on both my desktop PC and my laptop) the following steps helped to get unshackle to boot and run:
> > > 
> > > 1. if drive is encrypted (bitlocker or veracrypt), then disable drive encryption 
> > > 2. disable secure boot in BIOS
> > > 3. disable fast boot in BIOS
> > > 4. switch from windows UEFI -> legacy OS/custom OS in BIOS
> > > 
> > > In some BIOSes, 3 and 4 disable secure boot. 4 is necessary to allow booting into the unshackle USB (otherwise it doesn't appear in boot options).
> > > 
> > > So unshackle ran successfully, I rebooted, but after pressing shift five times on the login screen, nothing seemed to happen. It just seemed to disable my PIN and fingerprint reader logins (fingerprint reader login asked to use PIN, PIN said something went wrong and it needed to be reset). I ended up needing to log in with my password. After restarting and not changing anything, and not pressing shift five times, fingerprint and PIN worked fine. I removed fingerprint and PIN, re-ran unshackle again, rebooted, pressed shift five times on the lock screen, and no effect. My password was still necessary to log in.
> > 
> > If you have online account then its impossible to bypass the password so just create a new account with administrator permissions
> > Just type !shell it should open a cmd for you and type these commands
> > 
> > 
> > net user [username] [password] /add
> > net localgroup administrators [username] /add
> > 
> 
> I don't use any online Microsoft account. I'm using a local administrator account on all my computers.
> 
> I tested on both my Windows 11 desktop and my Windows 10 laptop.

Its stranger thing because it worked fine for me i even tried it on my old laptop it worked perfectly

**Comment by joe865** [comment]
I flashed with Rufus the latest version I noticed the drive doesn't show on uefi mode but when I switch bios to legacy support I could run unshackle on some other PC there was no option to switch to legacy

Although I go an error while trying to run unshackle and I wasn't successful with it.
![20230723_133825](https://github.com/Fadi002/unshackle/assets/59167122/efbc0a65-5530-44f4-8df1-0412849f7b5a)

**Comment by Fadi002** [comment]
> I flashed with Rufus the latest version I noticed the drive doesn't show on uefi mode but when I switch bios to legacy support I could run unshackle on some other PC there was no option to switch to legacy
> 
> Although I go an error while trying to run unshackle and I wasn't successful with it.
> ![20230723_133825](https://github.com/Fadi002/unshackle/assets/59167122/efbc0a65-5530-44f4-8df1-0412849f7b5a)
> 

Can you show me everything on the screen?

**Comment by joe865** [comment]
Sure
![20230723_140842](https://github.com/Fadi002/unshackle/assets/59167122/58b7ec8d-b9da-4b8c-811a-c23e01b24e5f)

**Comment by Fadi002** [comment]
> Sure
> ![20230723_140842](https://github.com/Fadi002/unshackle/assets/59167122/58b7ec8d-b9da-4b8c-811a-c23e01b24e5f)
> 

Try to burn the image using 
https://etcher.balena.io/

**Comment by joe865** [comment]
I got the same error

**Comment by Fadi002** [comment]
> I got the same error 

I guess you need to wait for a new update

**Comment by Kevin3-00** [comment]
> > I got the same error
> 
> I guess you need to wait for a new update

Even though I was the first to complain about this tool,I don't think all of these people could be wrong too.I think you need to recheck or just update it in general.

**Comment by Fadi002** [comment]
> > > I got the same error
> > 
> > I guess you need to wait for a new update
> 
> Even though I was the first to complain about this tool,I don't think all of these people could be wrong too.I think you need to recheck or just update it in general.

The problem that I'm using alpine linux and just put my tool at the startup but i will try my best to fix it

**Comment by Fadi002** [comment]
> > > I got the same error
> > 
> > I guess you need to wait for a new update
> 
> Even though I was the first to complain about this tool,I don't think all of these people could be wrong too.I think you need to recheck or just update it in general.

Can you try to boot into stock alpine linux ?
Here's the link : https://dl-cdn.alpinelinux.org/alpine/v3.18/releases/x86_64/alpine-standard-3.18.2-x86_64.iso

**Comment by 4ksr** [comment]
> Sure ![20230723_140842](https://user-images.githubusercontent.com/59167122/255395096-58b7ec8d-b9da-4b8c-811a-c23e01b24e5f.jpg)

If your CPU is intel gen from 11 to 13 make you have intel rst or vmb disabled or check the drivers

**Comment by dimon453** [comment]
Hey, you already know that rufus not allowing to select GPT mode, but all my work PCs and my personal laptop are from Dell, with new UEFI, that doesn't support legacy boot at all. And thumb drive with this ISO hasn't been initialised and not appears in boot options. Maybe there are some ways to convert this ISO to EFI-compatible, or write it in GPT mode, Maybe some EFI utilities, like ventoy may help? I'll try all and will edit this comment if something happends

**Comment by mgryka** [comment]
I've experienced the same issue with Rufus 3.0+ for various ISOs. I was able to successfully use Rufus 2.8 to create an unshackle USB, so I believe this is a problem originating with that version of Rufus rather than with unshackle.

**Comment by gruvX** [comment]
As i can understand this tool can boot only in legacy :(

**Comment by Fadi002** [comment]
> As i can understand this tool can boot only in legacy :(

it can boot in UEFI for me so idk
