### ISSUE TITLE
Are the effects of unshackle persistent?

### ISSUE THREAD

**Issue by mgryka** [Fadi002/unshackle#3]
After using the tool, will anyone be able to walk up to the machine in question and press shift 5 times to unlock or only while the USB is present?

Thanks!

**Comment by AdvDebug** [comment]
after choosing the "windows" option you can then eject/remove the USB and boot into the system, but if you want to do that again then you will have to do the same process because windows replaces "sethc.exe" which we replace with ours with the original one after some time.

**Comment by mgryka** [comment]
Awesome! Thanks for the quick reply!
