### ISSUE TITLE
Small Question

### ISSUE THREAD

**Issue by Ramy0021** [Fadi002/unshackle#8]
can i ask a small question?

**Comment by Fadi002** [comment]
> can i ask a small question?

Yes

**Comment by Fadi002** [comment]
> this thing is skidded 100%

Oh well, if it's the case that you asked, 'How do I use this?' I'm quite certain that you don't even know how to write a 'print hello world' code.

**Comment by Fadi002** [comment]
> 

well do something like this

**Comment by Fadi002** [comment]
> > well do something like this
> 
> is it huge?

well, can you explain the code ?

**Comment by Fadi002** [comment]
> 

do it

**Comment by Fadi002** [comment]
> i did it.

skid just go and cry
